export const landingTheme = {
  colors: {
    abyss: "#010512",
    deep: "#02081c",
    surface: "#0b2545",
    cyan: "#22e4ff",
    aqua: "#5ff7e0",
    violet: "#a78bfa",
    coral: "#ff7e9d",
    amber: "#ffb86b",
    text: "#eaf6ff",
    textSecondary: "rgba(234, 246, 255, 0.72)",
    textMuted: "rgba(234, 246, 255, 0.48)",
    line: "rgba(234, 246, 255, 0.12)",
    glass: "rgba(8, 24, 56, 0.58)",
  },
  radii: {
    small: "12px",
    medium: "18px",
    large: "24px",
    xlarge: "32px",
    pill: "999px",
  },
  spacing: {
    section: "clamp(5.5rem, 11vw, 9rem)",
    gutter: "clamp(1.25rem, 4vw, 2.5rem)",
  },
  motion: {
    enter: [0.16, 1, 0.3, 1] as const,
    duration: 0.7,
  },
} as const;

export const landingCssVariables = {
  "--color-abyss": landingTheme.colors.abyss,
  "--color-deep": landingTheme.colors.deep,
  "--color-surface": landingTheme.colors.surface,
  "--color-cyan": landingTheme.colors.cyan,
  "--color-aqua": landingTheme.colors.aqua,
  "--color-violet": landingTheme.colors.violet,
  "--color-coral": landingTheme.colors.coral,
  "--color-amber": landingTheme.colors.amber,
  "--color-text": landingTheme.colors.text,
  "--color-text-secondary": landingTheme.colors.textSecondary,
  "--color-text-muted": landingTheme.colors.textMuted,
  "--color-line": landingTheme.colors.line,
  "--color-glass": landingTheme.colors.glass,
  "--radius-small": landingTheme.radii.small,
  "--radius-medium": landingTheme.radii.medium,
  "--radius-large": landingTheme.radii.large,
  "--radius-xlarge": landingTheme.radii.xlarge,
  "--radius-pill": landingTheme.radii.pill,
  "--space-section": landingTheme.spacing.section,
  "--space-gutter": landingTheme.spacing.gutter,
} as CSSProperties;
import type { CSSProperties } from "react";
